language: python

python:
  - "2.7"

before_install:
    - sudo apt-get install python-virtualenv pkg-config zlib1g-dev libssl-dev build-essential protobuf-compiler libprotobuf-dev libgeos-dev python-matplotlib python-scipy gfortran libblas-dev liblapack-dev libatlas-base-dev libjpeg-dev libfreetype6-dev
    - pip install pep8
    - pip install numpy
    - pip install imposm.parser

install:
    - python setup.py -q install

script:
    # Don't fail if a line is longer than 80 characters (E501)
    - find . -name \*.py -exec pep8 --ignore=E501 --exclude='*/procedural_city_generation/*' {} +
    - ./run_tests.sh
