language: python

cache: pip

python:
  - "2.7"

before_install:
    - sudo apt-get install python-virtualenv pkg-config zlib1g-dev libssl-dev build-essential protobuf-compiler libprotobuf-dev libgeos-dev python-matplotlib python-scipy gfortran libblas-dev liblapack-dev libatlas-base-dev libjpeg-dev libfreetype6-dev
    - pip install pep8==1.7.0
    - pip install numpy==1.11.3
    - pip install imposm.parser==1.0.7
    - pip install python-slugify==1.2.1

install:
    - python setup.py -q install

script:
    # Don't fail if a line is longer than 80 characters (E501)
    - find . -name \*.py -exec pep8 --ignore=E501 --exclude='*/procedural_city_generation/*' {} +
    - ./run_tests.sh
